//
// Created by Rahul Yadav on 2020-01-04.
//

#ifndef PROJ_ANDROID_DEFINITIONS_H
#define PROJ_ANDROID_DEFINITIONS_H



#define MAIN_MENU_BG "HD1280/HelloWorld.png"
#define X_PIECE 8
#define O_PIECE 0
#define EMPTY_PIECE -1


#define STATE_PLAYING 98
#define STATE_PAUSED 97
#define STATE_WON 96
#define STATE_LOSE 95
#define STATE_PLACING_PIECE 94

#define O_WINNING_PIECE_FILEPATH "HD1280/OWin.png"
#define X_WINNING_PIECE_FILEPATH "HD1280/XWin.png"

#define PIECE_FADE_IN_TIME 0.5


#endif //PROJ_ANDROID_DEFINITIONS_H
